### ISSUE TITLE
不知道为什么出这个问题

### ISSUE THREAD

**Issue by www3com** [ant-tool/html-repath-webpack-plugin#1]
E:\dva-example-antd-mobile-master\node_modules\html-repath-webpack-plugin\lib\util.js:27
    if (forceRelative && !(0, _isUrl2.default)(source) && source.charAt(0) === '/') {
                                                                ^

TypeError: Cannot read property 'charAt' of undefined
    at Object.<anonymous> (E:\dva-example-antd-mobile-master\node_modules\html-repath-webpack-plugin\lib\util.js:27:65)
    at initialize.exports.each (E:\dva-example-antd-mobile-master\node_modules\cheerio\lib\api\traversing.js:294:24)
    at fixSourcePath (E:\dva-example-antd-mobile-master\node_modules\html-repath-webpack-plugin\lib\util.js:25:15)
    at fixAssetsInHtml (E:\dva-example-antd-mobile-master\node_modules\html-repath-webpack-plugin\lib\util.js:49:3)
    at E:\dva-example-antd-mobile-master\node_modules\html-repath-webpack-plugin\lib\index.js:83:51
    at Array.forEach (native)
    at Compiler.<anonymous> (E:\dva-example-antd-mobile-master\node_modules\html-repath-webpack-plugin\lib\index.js:71:19)
    at Compiler.applyPluginsAsync (E:\dva-example-antd-mobile-master\node_modules\tapable\lib\Tapable.js:71:13)
    at Compiler.emitAssets (E:\dva-example-antd-mobile-master\node_modules\webpack\lib\Compiler.js:226:7)
    at Compiler.<anonymous> (E:\dva-example-antd-mobile-master\node_modules\webpack\lib\Compiler.js:184:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\software\nodejs\node.exe" "D:\software\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! @ build: `atool-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script 'atool-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     atool-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\dva-example-antd-mobile-master\npm-debug.log

**Comment by soda-x** [comment]
提示没有 charAt 这个方法，难道传入的不是一个字符串么?
